# Generated by Django 3.0.8 on 2020-07-10 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Search.Product'),
        ),
    ]
