# Generated by Django 3.0.8 on 2020-07-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchpageads',
            old_name='header',
            new_name='Name',
        ),
    ]
