# Generated by Django 3.0.8 on 2020-07-13 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertisements', '0002_auto_20200713_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchpageads',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='searchpageads',
            old_name='image_url',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='searchpageads',
            old_name='redirect_url',
            new_name='Link',
        ),
        migrations.RenameField(
            model_name='searchpageads',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='searchpageads',
            old_name='seller',
            new_name='Seller',
        ),
    ]
