# Generated by Django 3.0.8 on 2020-07-10 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.CharField(blank=True, max_length=10, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Link', models.CharField(blank=True, max_length=300, null=True)),
                ('Image', models.CharField(blank=True, max_length=300, null=True)),
                ('Seller', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_value', models.CharField(max_length=100, null=True)),
                ('Search_User', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
    ]
