# Generated by Django 3.0.8 on 2020-07-07 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='created',
        ),
        migrations.AddField(
            model_name='search',
            name='Search_User',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='search',
            name='Search_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
