# Generated by Django 3.0.8 on 2020-07-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
