# Generated by Django 3.0.8 on 2020-07-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20200710_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='Frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
